### ISSUE TITLE
Background shadow

### ISSUE THREAD

**Issue by zishanj** [richrad/Popover#2]
Just checked this sample and it works great. Wondering if there is a way to get rid from background shadow that appears below the popup. It looks very awful.

**Comment by richrad** [comment]
I don't see anything in `UIPopoverController` or `UIPopoverPresentationControllerDelegate` that would let you do that but it's probably possible if you're willing to get in there and mess around with the view hierarchy. In general though I wouldn't recommend trying to change the way a standard (i.e. Apple provided) control looks beyond what Apple grants you access to since (even if their thing is ugly) it makes your app look "off" and you never know what update they'll ship that breaks your hack.
